name: Test the Application

on: push

jobs:
  App:
    name: Check the app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: test the app
        run: python tests_porject/test-add-users.py
